name: publish

on:
    workflow_run:
        workflows: [ "release" ]
        types:
            - completed

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18
                    registry-url: https://npm.pkg.github.com/
            -   run: npm install
                env:
                    NODE_AUTH_TOKEN: ${{secrets.PAT}}
            -   run: npm run build
            -   uses: actions/upload-artifact@v3
                with:
                    name: conventional-commit-package
                    path: lib
                    retention-days: 1

    publish:
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/setup-node@v3
                with:
                    node-version: 18
                    registry-url: https://npm.pkg.github.com/
            -   uses: actions/download-artifact@v3
                with:
                    name: conventional-commit-package
                    path: lib
            -   run: npm publish ./lib
                env:
                    NODE_AUTH_TOKEN: ${{secrets.PAT}}
